<#
.SYNOPSIS
    Copies the freshly built MeshAgent binaries & provisioning manifest into the local MeshCentral data directory.

.DESCRIPTION
    MeshCentral prefers the binaries that live under meshcentral-data\signedagents (if present) and then falls back to
    meshcentral-data\agents. This helper mirrors our StealthLab outputs (x86/x64 EXE + .msh) into both locations so
    the MeshCentral download links always return our customized diaghost build instead of the stock upstream agent.

    Example:
        pwsh .\tools\Publish-MeshCentralAgents.ps1

.PARAMETER MeshCentralDataPath
    Root of the MeshCentral data directory (defaults to ..\meshcentral-data relative to the repo).

.PARAMETER X64Binary
    Path to the x64 StealthLab executable we just built.

.PARAMETER X86Binary
    Path to the x86 StealthLab executable we just built.

.PARAMETER ProvisioningManifest
    The .msh file generated by build.ps1 for StealthLab (copied next to the server binaries for convenience).
#>
[CmdletBinding()]
param(
    [string]$MeshCentralDataPath = (Join-Path $PSScriptRoot '..\..\meshcentral-data'),
    [string]$X64Binary = (Join-Path $PSScriptRoot '..\meshservice\x64\StealthLab\MeshService-2022.exe'),
    [string]$X86Binary = (Join-Path $PSScriptRoot '..\meshservice\StealthLab\MeshService-2022.exe'),
    [string]$ProvisioningManifest = (Join-Path $PSScriptRoot '..\meshservice\x64\StealthLab\MeshService-2022.msh')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-FullPath([string]$Path) {
    $resolved = Resolve-Path -LiteralPath $Path -ErrorAction Stop
    return $resolved.ProviderPath
}

function Copy-WithHash {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string[]]$Destinations,
        [Parameter(Mandatory = $true)][string]$Label
    )

    $sourceHash = (Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash
    foreach ($dest in $Destinations) {
        $destDir = Split-Path -Path $dest -Parent
        if (-not (Test-Path -LiteralPath $destDir)) {
            New-Item -ItemType Directory -Path $destDir -Force | Out-Null
        }
        Copy-Item -LiteralPath $Source -Destination $dest -Force
    }
    Write-Host ("[INFO] {0} published (SHA256 {1})" -f $Label, $sourceHash) -ForegroundColor Cyan
}

$meshCentralData = Resolve-FullPath $MeshCentralDataPath
$signedAgentsDir = Join-Path $meshCentralData 'signedagents'
$agentsDir = Join-Path $meshCentralData 'agents'

foreach ($dir in @($signedAgentsDir, $agentsDir)) {
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

$x64Source = Resolve-FullPath $X64Binary
$x86Source = Resolve-FullPath $X86Binary
$mshSource = Resolve-FullPath $ProvisioningManifest

Copy-WithHash -Source $x64Source -Label 'MeshService64.exe' -Destinations @(
    (Join-Path $signedAgentsDir 'MeshService64.exe'),
    (Join-Path $agentsDir 'MeshService64.exe'))

Copy-WithHash -Source $x86Source -Label 'MeshService.exe' -Destinations @(
    (Join-Path $signedAgentsDir 'MeshService.exe'),
    (Join-Path $agentsDir 'MeshService.exe'))

Copy-WithHash -Source $mshSource -Label 'WinDiagnosticHost.msh' -Destinations @(
    (Join-Path $meshCentralData 'WinDiagnosticHost.msh'),
    (Join-Path $agentsDir 'MeshService-2022.msh'))

Write-Host "[OK] MeshCentral agent drop complete. Restart MeshCentral to pick up the new binaries." -ForegroundColor Green
